services:
  - type: web
    name: exam-system-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: "https://exam-system-frontend-phi.vercel.app"
      - key: DATABASE_URL
        sync: false # Must be set manually in Render Dashboard for security
